### ISSUE TITLE
Can't Open In-Game Calendar

### ISSUE THREAD

**Issue by ridius** [XyzKangUI/Lorti-TBCC-WOTLKC#2]
Lorti-UI hides the day button on the mini-map. This button is required to show the calendar.

/calendar does not work in-game.

**Comment by XyzKangUI** [comment]
Thanks for the report. Fixed it.

**Comment by ridius** [comment]
Confirmed fixed!

Thanks for keeping this addon up-to-date! It's truly appreciated.
